def generate_readme(brief='To generate an app with certain specifications',round=1,task='Auto Web App'):
    if round ==1:
        return f"""# {task} - An LLM Generated Web Application
    
## Summary
This web application is automatically generated by a large language model (LLM) based on the following detailed user-provided brief : 
```
{brief}
```
The system analyzes the brief and produces the complete source code for a minimal, responsive, and functional single-page website, built using HTML, CSS, and JavaScript. The app may include additional assets such as images or data files necessary for its features.  
Alongside the main webpage (`index.html`), the generated package includes:
- `brief.txt`: The original user brief describing the app's intended functionality.
- `LICENSE`: License information governing the use of the generated content.
- `Attachments`: Additional resource files referenced by the webpage.
This structure allows easy deployment, customization, and understanding of the generated application.  
Currently the app is deployed on the GitHub Pages of this repository. 
## Setup
No build or installation is required.
1. Simply open the GitHub Pages url to interact with the live app or download the  GitHub repository directory on a local system and open it in any modern web browser to view and interact with the application.
2. All referenced assets and attachments are included and linked relative to the HTML file.  
To update or customize the app:
1. Clone or download this repository.
2. Modify `index.html`, `brief.txt`, or attachments as needed.
3. Commit and push changes to the GitHub repository branch configured for GitHub Pages.
4. The live site will update automatically within minutes.
No additional build or server setup is required.
## Usage
- Open the live site URL in any modern web browser.
- Review `brief.txt` to understand the purpose and features implemented.
- Modify `index.html` and other files as needed to customize the app.
- Refer to the `LICENSE` file for usage rights. 
- All external dependencies (e.g., CSS frameworks, JS libraries) are loaded via [jsDelivr CDN](https://www.jsdelivr.com/) for optimal reliability.
- Attachments are stored and referenced relative to `index.html` for ease of management. 
## Code Explanation
- **index.html**: Contains -
  - **HTML structure**: Semantic layout following the provided brief. 
  - **CSS styling**: linked stylesheets,typically loaded via reliable CDN (jsDelivr) for libraries like Bootstrap. 
  - **JavaScript**: Interactive features implemented with vanilla JS or light frameworks as per the brief.
- **brief.txt**: Provides context by detailing the original user brief and ensures transparency about the app's intent.
- **LICENSE**: The MIT License which specifies the terms under which the app can be used and shared.
- **Attachments**: Additional files (images, CSVs, JSON) included as needed for full app functionality.  
The app emphasizes clean, readable code and minimal external dependencies for performance and maintainability.
## License
This generated application and its contents are provided under the [MIT License](LICENSE).  
```
MIT License © 2025 23f3001761
```
## Additional Notes
- External libraries and assets are loaded via jsDelivr CDN to ensure stability and performance.
- The app is designed to be minimal, efficient, and easily extendable.
- For further customization or feature enhancements, modify the files directly and push updates to GitHub.
"""

    else:
        return f"""# {task} - An LLM Generated Web Application - Revised Version 
## Summary
This web application is automatically generated and updated by a large language model (LLM) based on the following detailed user-provided brief : 
```
{brief}
```
The system analyzes the brief and produces the complete source code for a minimal, responsive, and functional single-page website, built using HTML, CSS, and JavaScript. The app may include additional assets such as images or data files necessary for its features.  
Alongside the main webpage (`index.html`), the generated package includes:
- `brief.txt`: The original user brief describing the app's intended functionality.
- `LICENSE`: License information governing the use of the generated content.
- `Attachments`: Additional resource files referenced by the webpage.
This structure allows easy deployment, customization, and understanding of the generated application.  
Currently the app is deployed on the GitHub Pages of this repository. 
## Setup
No build or installation is required.
1. Simply open the GitHub Pages url to interact with the live app or download the  GitHub repository directory on a local system and open it in any modern web browser to view and interact with the application.
2. All referenced assets and attachments are included and linked relative to the HTML file.  
To update or customize the app:
1. Clone or download this repository.
2. Modify `index.html`, `brief.txt`, or attachments as needed.
3. Commit and push changes to the GitHub repository branch configured for GitHub Pages.
4. The live site will update automatically within minutes.
No additional build or server setup is required.
## Usage
- Open the live site URL in any modern web browser.
- Review `brief.txt` to understand the purpose and features implemented.
- Modify `index.html` and other files as needed to customize the app.
- Refer to the `LICENSE` file for usage rights. 
- All external dependencies (e.g., CSS frameworks, JS libraries) are loaded via [jsDelivr CDN](https://www.jsdelivr.com/) for optimal reliability.
- Attachments are stored and referenced relative to `index.html` for ease of management. 
## Code Explanation
- **index.html**: Contains -
  - **HTML structure**: Semantic layout following the provided brief. 
  - **CSS styling**: linked stylesheets,typically loaded via reliable CDN (jsDelivr) for libraries like Bootstrap. 
  - **JavaScript**: Interactive features implemented with vanilla JS or light frameworks as per the brief.
- **brief.txt**: Provides context by detailing the original user brief and ensures transparency about the app's intent.
- **LICENSE**: The MIT License which specifies the terms under which the app can be used and shared.
- **Attachments**: Additional files (images, CSVs, JSON) included as needed for full app functionality.  
The app emphasizes clean, readable code and minimal external dependencies for performance and maintainability.
## License
This generated application and its contents are provided under the [MIT License](LICENSE).  
```
MIT License © 2025 23f3001761
```
## Additional Notes
- External libraries and assets are loaded via jsDelivr CDN to ensure stability and performance.
- The app is designed to be minimal, efficient, and easily extendable.
- For further customization or feature enhancements, modify the files directly and push updates to GitHub.
"""
